version: '3.8'
services:
  react-ui:
    build:
      context: ./react-ui
      dockerfile: Dockerfile
    container_name: react-ui
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    stdin_open: true
    volumes:
      - /react-ui/node_modules
      - ./react-ui:/react-ui
       
