version: '3.8'
services:
  django-api:
    build:
      context: ./django-api
      dockerfile: Dockerfile
    container_name: django-api
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - "80:80"
    volumes: ['./django-api:/django-api']
