version: "3.8"

services:
    sql:
      image: mysql:5.7
      container_name: "sql"
      environment:
        MYSQL_DATABASE: "db"
        MYSQL_USER: "user"
        MYSQL_PASSWORD: "12345678"
        MYSQL_ROOT_PASSWORD: "12345678"
      ports:
        - "3306:3306"
      volumes: 
        - ./mysql/db:/var/lib/mysql
